### ISSUE TITLE
Release description into kinetic and melodic

### ISSUE THREAD

**Issue by wxmerkt** [pal-robotics/talos_robot#2]
Hi guys,
We are interested in starting to use the description for planning and unit testing - and being able to install it directly from binaries would be fantastic.

We are very happy to help with release etc. if desired.

Best wishes,
Wolfgang

**Comment by v-lopez** [comment]
Sure thing, we'll take a look this week, it should be pretty straightforward.

**Comment by wxmerkt** [comment]
Thank you for the swift response, this is awesome!

**Comment by v-lopez** [comment]
We're working on it, a lot of dependencies need to be released.

For melodic, at least one branch of the dependency tree is out of our control: https://github.com/orocos/rtt_ros_integration/issues/115

**Comment by wxmerkt** [comment]
Hi @v-lopez, 
Would it work for just releasing the `talos_description` - without the `talos_robot` etc. packages (which are only needed on the physical robots anyway)? From a quick scan the dependency tree appears to be:

```
talos_description
    rostest
    urdf_test
    talos_description_inertial
        xacro
    talos_description_calibration
        xacro
```

All of these are already released :-)

Thanks!
Wolfgang

**Comment by v-lopez** [comment]
Do you know if there's a standard procedure for releasing a single package? Or should I just edit the gbp files?

**Comment by wxmerkt** [comment]
In the `rosdistro` entry you can specify which packages you'd like. For an example see here:

https://github.com/ros/rosdistro/blob/940f878c830b0fdbd6964b42434979dd2837c325/melodic/distribution.yaml#L5386-L5397

**Comment by olivier-stasse** [comment]
Dear Wolfgang,
We have packaged talos-robot in an apt-repository for various distros:
http://robotpkg.openrobots.org/rbulk/robotpkg-wip/wip/talos-robot/index.html#talos-robot-1.0.2

The problem is the license.  As it is Propietary we are conservative and only providing it through a private repo protected by a password. In the frame of Memmo we can, I guess, provide it to you.

For kinetic we can provide the full simulation packages with gazebo on kinetic.
Best,
Olivier.

**Comment by v-lopez** [comment]
I've requested the release of talos_description as suggested.

https://github.com/ros/rosdistro/pull/19805
https://github.com/ros/rosdistro/pull/19806

Regarding the license, we'll review it, by default we make everything proprietary, but we'll review the software we've made open source.

**Comment by wxmerkt** [comment]
Thank you very much @v-lopez for the speedy release :-)

Dear Olivier,
Thank you very much for the offer - I think we will come back to you on this for Memmo around the time of the winter school. For now we are good with source of the description as in this repository - or the released binaries - for planning. For simulation next spring we'll be in touch.

Happy holidays,
Wolfgang

**Comment by v-lopez** [comment]
Actually the proper way for ignoring packages is described here: https://answers.ros.org/question/66545/to-ignore-some-pkgs-upon-release-by-bloom/

An example can be seen here: https://github.com/ros-gbp/moveit-release

My last release was pushed back for this reason, I'm resubmitting.
